### ISSUE TITLE
Improve error reporting for missing tools

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#115]
Attempting to download the image for a tool that isn't registered with BugZoo produces an ugly and unhelpful error:

```
$ bugzoo tool download name-of-tool-that-does-not-exist
downloading tool: name-of-tool-that-does-not-exist
Traceback (most recent call last):
  File "/home/chris/git/bugzoo/bin/bugzoo", line 11, in <module>
    load_entry_point('bugzoo==0.0.1', 'console_scripts', 'bugzoo')()
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 389, in main
    args.func(args)
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 273, in <lambda>
    cmd.set_defaults(func=lambda args: download_tool(rbox, args.tool, args.force))
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 155, in download_tool
    rbox.tools[name].download(force=force)
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/manager.py", line 103, in __getitem__
    raise IndexError
IndexError
```

The CLI should catch this error and print a nicer error message.

**Comment by ChrisTimperley** [comment]
Added exception handling into tools-related CLI commands.
