### ISSUE TITLE
Docker not installed - got this

### ISSUE THREAD

**Issue by joerenzullo** [squaresLab/BugZoo#117]
```
[jvrenzul@agave1:~]$ bugzoo bug list
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
WARNING: use `build` property rather than `docker` to provide build instructions.
Traceback (most recent call last):
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/transport/unixconn.py", line 46, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/jvrenzul/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/transport/unixconn.py", line 46, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jvrenzul/.local/bin/bugzoo", line 11, in <module>
    load_entry_point('bugzoo==0.0.1', 'console_scripts', 'bugzoo')()
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/bugzoo-0.0.1-py3.6.egg/bugzoo/cli.py", line 389, in main
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/bugzoo-0.0.1-py3.6.egg/bugzoo/cli.py", line 380, in <lambda>
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/bugzoo-0.0.1-py3.6.egg/bugzoo/cli.py", line 120, in list_bugs
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/bugzoo-0.0.1-py3.6.egg/bugzoo/bug.py", line 219, in installed
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/bugzoo-0.0.1-py3.6.egg/bugzoo/build.py", line 129, in installed
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/models/images.py", line 212, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/api/image.py", line 241, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/jvrenzul/.local/lib/python3.6/site-packages/docker-3.0.0-py3.6.egg/docker/api/client.py", line 192, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/jvrenzul/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by ChrisTimperley** [comment]
This error output is particularly egregious and unhelpful. To rectify the issue, two things should happen:

- [ ]  the code responsible for first establishing a connection to the Docker server (recently added in 2.1.7) should attempt to catch the `requests.exceptions.ConnectionError` and instead raise a `DockerConnectionError` exception, defined by BugZoo.
- [ ] the CLI should do a better job of catching unhandled exceptions and transforming them into readable error messages. Further, unhandled exceptions should be recorded to a log file for the CLI session via `logger.exception`.

**Comment by PERRO10** [comment]
Hi guys,
I have same problem and and I can not solve it.

$ bugzoo source add another-manybugs path/to/manybugs
Traceback (most recent call last):
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perrini/.local/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/perrini/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/perrini/.local/bin/bugzoo", line 11, in <module>
    sys.exit(main())
  File "/home/perrini/.local/lib/python3.5/site-packages/bugzoo/cli/__init__.py", line 538, in main
    parser = build_parser()
  File "/home/perrini/.local/lib/python3.5/site-packages/bugzoo/cli/__init__.py", line 312, in build_parser
    rbox = BugZoo()
  File "/home/perrini/.local/lib/python3.5/site-packages/bugzoo/manager.py", line 75, in __init__
    assert self.__docker.ping()
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/api/daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/perrini/.local/lib/python3.5/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/perrini/.local/lib/python3.5/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/perrini/.local/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/perrini/.local/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/perrini/.local/lib/python3.5/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Any helps?
