### ISSUE TITLE
Unexpected failure during bug validation

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#119]
```
(bugzoo) chris@chris-Blade:~/git/bugzoo$ bugzoo bug validate manybugs:php:2012-03-19-53e3467ff2-9a460497da
validating bug: manybugs:php:2012-03-19-53e3467ff2-9a460497da
Compiling...                                                                [OK]
Running test: p1...                                           [UNEXPECTED: FAIL]
Traceback (most recent call last):
  File "/home/chris/git/bugzoo/bin/bugzoo", line 11, in <module>
    load_entry_point('bugzoo==0.0.1', 'console_scripts', 'bugzoo')()
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 413, in main
    args.func(args)
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 360, in <lambda>
    cmd.set_defaults(func=lambda args: validate_bug(rbox, args.bug, args.verbose))
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/cli.py", line 83, in validate_bug
    if bug.validate(verbose=verbose):
  File "/home/chris/git/bugzoo/lib/python3.6/site-packages/bugzoo/bug.py", line 280, in validate
    response = textwrap.indent(outcome.response.output, ' ' * 4)
  File "/usr/lib/python3.6/textwrap.py", line 482, in indent
    return ''.join(prefixed_lines())
  File "/usr/lib/python3.6/textwrap.py", line 481, in prefixed_lines
    yield (prefix + line if predicate(line) else line)
TypeError: must be str, not bytes
```

**Comment by ChrisTimperley** [comment]
Due to output produced by a command execution not being decoded from a byte-stream to a string. Fixed.
