### ISSUE TITLE
error adding ManyBugs source

### ISSUE THREAD

**Issue by joerenzullo** [squaresLab/BugZoo#122]
2 issues - first the documentation still mentions the old location of ManyBugs

when that's changed to the new location, though, I still ran into the following

```
$ pip3 install bugzoo
$ bugzoo --version
2.0.0
```

Ran into this issue with:
```
$ bugzoo source add https://github.com/squaresLab/ManyBugs
```

```
joe@b120ba:~$ bugzoo source add https://github.com/squaresLab/ManyBugs
Traceback (most recent call last):
  File "/home/joe/.local/bin/bugzoo", line 11, in <module>
    sys.exit(main())
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 380, in main
    args.func(args)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 223, in <lambda>
    cmd.set_defaults(func=lambda args: add_source(rbox, args.source))
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 25, in add_source
    rbox.sources.add(src)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 157, in add
    src = self.__download(url)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 139, in __download
    return self.load(url)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 148, in load
    return Source.from_dict(self, url, yml)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 16, in from_dict
    return bugzoo.dataset.Dataset.from_dict(manager, url, d)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/dataset.py", line 20, in from_dict
    return Dataset(manager, url, name)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/dataset.py", line 27, in __init__
    self.scan()
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/dataset.py", line 41, in scan
    bug = Bug.from_file(self, fn)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/bug.py", line 72, in from_file
    raise Exception('No compilation instructions provided for bug: {}'.format(name))
Exception: No compilation instructions provided for bug: 2009-08-16-3fe0caeada-39a362ae9d
```

Ran the same command again to see if it responded the same way - new error message!

```
joe@b120ba:~$ bugzoo source add https://github.com/squaresLab/ManyBugs
Traceback (most recent call last):
  File "/home/joe/.local/bin/bugzoo", line 11, in <module>
    sys.exit(main())
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 380, in main
    args.func(args)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 223, in <lambda>
    cmd.set_defaults(func=lambda args: add_source(rbox, args.source))
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/cli.py", line 25, in add_source
    rbox.sources.add(src)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 157, in add
    src = self.__download(url)
  File "/home/joe/.local/lib/python3.6/site-packages/bugzoo/source.py", line 137, in __download
    assert not os.path.exists(abs_path)
AssertionError
```

**Comment by ChrisTimperley** [comment]
The latest "stable" version is a bit behind the current development version. I'll look into using Travis to automatically push builds from the `master` branch to PyPi.

The second error is due to some poor error handling in an earlier version of BugZoo. After downloading the source to your machine (specifically, to your local `.bugzoo/sources` directory), BugZoo fails to parse some of the manifest files due to a breaking change in the file format, causing an exception to be thrown. Unfortunately, the exception is thrown in the middle of the installation process, leaving `.bugzoo/sources` in an incoherent state, thus causing all future interactions with BugZoo to raise an exception. That bug *should* be fixed. I guess I could write a test case to actually ensure that the inconsistency issues have vanished.

**Comment by ChrisTimperley** [comment]
Fixed URL for ManyBugs and GenProg in both the documentation and the README.

**Comment by ChrisTimperley** [comment]
Modified the Travis file to automatically push tagged releases to PyPi. Installing BugZoo via `pip3 install bugzoo` should yield version 1.0.1.
