### ISSUE TITLE
`bug validate` command fails on server

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#139]
```
chris@clegoues-ubuntu-vm1:~/bugzoo$ bugzoo bug validate manybugs:lighttpd:1913-1914
validating bug: manybugs:lighttpd:1913-1914
Compiling...                                                                [OK]
Running test: p10...                                          [UNEXPECTED: FAIL]

    OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.5/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/home/chris/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localunixsocket/v1.35/containers/8ee2552e8bb5417c1ea5b33ecf39d846b609675fe334071367225f8cbf744288/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/.local/bin/bugzoo", line 9, in <module>
    load_entry_point('bugzoo==0.0.1', 'console_scripts', 'bugzoo')()
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/cli.py", line 441, in main
    args.func(args)
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/cli.py", line 388, in <lambda>
    cmd.set_defaults(func=lambda args: validate_bug(rbox, args.bug, args.verbose))
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/cli.py", line 83, in validate_bug
    if bug.validate(verbose=verbose):
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/bug.py", line 276, in validate
    outcome = c.execute(t)
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/container.py", line 306, in execute
    response = self.command(cmd, ctx, stderr=True)
  File "/home/chris/.local/lib/python3.5/site-packages/bugzoo/container.py", line 234, in command
    response = client.api.exec_create(self.__container.id, cmd, stdout=stdout, stderr=stderr)
  File "/home/chris/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/chris/.local/lib/python3.5/site-packages/docker/api/exec_api.py", line 80, in exec_create
    return self._result(res, True)
  File "/home/chris/.local/lib/python3.5/site-packages/docker/api/client.py", line 229, in _result
    self._raise_for_status(response)
  File "/home/chris/.local/lib/python3.5/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/chris/.local/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Container 8ee2552e8bb5417c1ea5b33ecf39d846b609675fe334071367225f8cbf744288 is not running")
```

**Comment by ChrisTimperley** [comment]
Caused by using an outdated version of BugZoo.
