### ISSUE TITLE
Python compilation issues

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#16]
python-bug-69368-69372 fails to compile.

```
$ cd python
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
$ make clean
$ make
...
Python/peephole.c: In function ‘PyCode_Optimize’:
Python/peephole.c:6313:28: warning: ‘tmp___14’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                         if (tmp___14) {
                            ^
/tmp/cccoXo6w.s: Assembler messages:
/tmp/cccoXo6w.s:2526: Error: symbol `stat64' is already defined
/tmp/cccoXo6w.s:2554: Error: symbol `lstat64' is already defined
/tmp/cccoXo6w.s:2582: Error: symbol `fstat64' is already defined
/tmp/cccoXo6w.s:2610: Error: symbol `fstatat64' is already defined
Makefile:1199: recipe for target 'Python/peephole.o' failed
make: *** [Python/peephole.o] Error 1
```

**Comment by ChrisTimperley** [comment]
May be due to an incompatibility issue between older glibc libraries and the C99 standard: http://www.spinics.net/lists/fio/msg01621.html

**Comment by ChrisTimperley** [comment]
Devised a partial fix:

```
$ cd python
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32 -std=gnu99 -fgnu89-inline" "CXXFLAGS=-m32" "LDFLAGS=-m32"
$ make clean
$ make
...
Python build finished, but the necessary bits to build these modules were not found:
_bz2               _ssl               _tkinter
ossaudiodev        readline
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_curses            _curses_panel      _dbm
_gdbm              _sqlite3

running build_scripts
copying and adjusting /vagrant/benchmarks/python-bug-69368-69372/python/Tools/scripts/pydoc3 -> build/scripts-3.3
copying and adjusting /vagrant/benchmarks/python-bug-69368-69372/python/Tools/scripts/idle3 -> build/scripts-3.3
copying and adjusting /vagrant/benchmarks/python-bug-69368-69372/python/Tools/scripts/2to3 -> build/scripts-3.3
renaming build/scripts-3.3/pydoc3 to build/scripts-3.3/pydoc3.3
renaming build/scripts-3.3/idle3 to build/scripts-3.3/idle3.3
renaming build/scripts-3.3/2to3 to build/scripts-3.3/2to3-3.3
/usr/bin/install -c -m 644 ./Tools/gdb/libpython.py python.exe-gdb.py
```

It looks like a few missing libraries are needed to build the rest of the modules.

**Comment by ChrisTimperley** [comment]
Suddenly unable to make at all:

```
$ make clean
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32 -std=gnu99 -fgnu89-inline" "CXXFLAGS=-m32" "LDFLAGS=-m32"
$ make
./Parser/asdl_c.py -h ./Include ./Parser/Python.asdl
Traceback (most recent call last):
  File "./Parser/asdl_c.py", line 1214, in <module>
    main(args[0])
  File "./Parser/asdl_c.py", line 1158, in main
    mod.version = get_file_revision(srcfile)
  File "./Parser/asdl_c.py", line 1142, in get_file_revision
    p = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:616: recipe for target 'Include/Python-ast.h' failed
```

Interestingly, we are able to make once again when starting again with a fresh python directory (from the ManyBugs website). The problem can be replicating by carrying out the following:

```
$ wget http://repairbenchmarks.cs.umass.edu/ManyBugs/scenarios/python-bug-69368-69372.tar.gz
$ tar -xvf python-bug-69368-69372.tar.gz
$ cd python-bug-69368-69372/python
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32 -std=gnu99 -fgnu89-inline" "CXXFLAGS=-m32" $ "LDFLAGS=-m32"
$ make clean
$ make
$ cd ../
$ cp python pycopy -r
$ make clean
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32 -std=gnu99 -fgnu89-inline" "CXXFLAGS=-m32" "LDFLAGS=-m32"
$ make
./Parser/asdl_c.py -h ./Include ./Parser/Python.asdl
Traceback (most recent call last):
  File "./Parser/asdl_c.py", line 1214, in <module>
    main(args[0])
  File "./Parser/asdl_c.py", line 1158, in main
    mod.version = get_file_revision(srcfile)
  File "./Parser/asdl_c.py", line 1142, in get_file_revision
    p = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:616: recipe for target 'Include/Python-ast.h' failed
```

**Comment by ChrisTimperley** [comment]
After a bit more investigation, it appears the problem only occurs when the ManyBugs archive is untar-ed within the F22 VM. Attempting to do so yields only a partial extraction, producing the following errors:

```
...
tar: python-bug-69368-69372/python/build/temp.linux-i686-3.3/libffi/include/ffitarget.h: Cannot create symlink to ‘/root/mountpoint-genprog/genprog-many-bugs/python-bug-69368-69372/python/Modules/_ctypes/libffi/src/x86/ffitarget.h’: Protocol error
tar: python-bug-69368-69372/python/build/temp.linux-i686-3.3/libffi/include/ffi_common.h: Cannot create symlink to ‘/root/mountpoint-genprog/genprog-many-bugs/python-bug-69368-69372/python/Modules/_ctypes/libffi/include/ffi_common.h’: Protocol error
tar: Exiting with failure status due to previous errors
```

May need to extract on Cygwin host machine, replace symbolic links with appropriate files, and re-archive. Let's find out!

**Comment by ChrisTimperley** [comment]
Tidied up original ManyBugs tar by removing `python/build` contents and the `python/.hg` directory. Extracts without any issues on F22.

```
$ wget http://repairbenchmarks.cs.umass.edu/ManyBugs/scenarios/python-bug-69368-69372.tar.gz
$ tar -xvf python-bug-69368-69372.tar.gz
$ cd python-bug-69368-69372
$ rm python/build/* -r
$ rm python/.hg -r
$ cd ../
$ tar -cvf python-bug-69368-69372.tar.gz python-bug-69368-69372
```

**EDIT:** Still refuses to work whenever the archive extraction occurs in F22.

**Comment by ChrisTimperley** [comment]
Solved archive extraction problems. Lack of support for symbolic links in synced directories was the cause of the fault. Python now compiles, albeit with some modules missing. After installing the missing libraries, everything should be okay.

**Comment by ChrisTimperley** [comment]
Compiles ncurses and sqlite modules after modification to F22 provisioning script.

```
Python build finished, but the necessary bits to build these modules were not found:
_bz2               _ssl               _tkinter        
ossaudiodev        readline                           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_dbm               _gdbm
```

**Comment by ChrisTimperley** [comment]
`_gdbm` now builds, but `_dbm` is still being stubborn. Perhaps this is related? https://bugs.python.org/issue15044

**Comment by ChrisTimperley** [comment]
Fixed `_dbm` compilation issue by including `--with-dbmliborder=gdbm` in the configure call.

**Comment by ChrisTimperley** [comment]
`_ssl` now  installs after installing `openssl-devel.i686`

**Comment by ChrisTimperley** [comment]
Installed Tcl/Tk via `sudo dnf install tcl.i686 tcl-devel.i686 tk.i686 tk-devel.i686`, but now `_tkinter` fails to build (rather than refusing to build due to missing components).

**Comment by ChrisTimperley** [comment]
Reduced build errors to those shown below after installing `readline.i686` and `readline-devel.i686`.

```
Python build finished, but the necessary bits to build these modules were not found:
_bz2               ossaudiodev                        
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_tkinter
```

**Comment by ChrisTimperley** [comment]
Several test cases return an unexpected result.

```
$ cat sanity.results | grep "BAD"
p31 - FAIL (BAD)
p34 - FAIL (BAD)
p57 - FAIL (BAD)
p65 - FAIL (BAD)
p66 - FAIL (BAD)
p96 - FAIL (BAD)
p139 - FAIL (BAD)
p144 - FAIL (BAD)
p187 - FAIL (BAD)
p203 - FAIL (BAD)
p227 - FAIL (BAD)
p247 - FAIL (BAD)
p252 - FAIL (BAD)
p257 - FAIL (BAD)
p268 - FAIL (BAD)
p272 - FAIL (BAD)
p273 - FAIL (BAD)
```

Status of compilation:

```
Python build finished, but the necessary bits to build these modules were not found:
ossaudiodev                                           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_tkinter
```

List of necessary modules can be found here: http://forums.fedoraforum.org/archive/index.php/t-277057.html

**Comment by ChrisTimperley** [comment]
SSL test case failures may be due to SSL 3 incompatibilities: https://bugs.python.org/issue23965

**Comment by ChrisTimperley** [comment]
Fixed `_tkinter` compilation failure by installing `libX11-dev.i686`.

**Comment by ChrisTimperley** [comment]
Python compiles fine. `ossaudiodev` is missing, but shouldn't be required by any of the test cases.
