### ISSUE TITLE
Error on logging

### ISSUE THREAD

**Issue by afsafzal** [squaresLab/BugZoo#264]
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "example/hello_world.py", line 181, in <module>
    run_single_mission(sandbox, mission)
  File "example/hello_world.py", line 24, in run_single_mission
    res = sandbox.run(mission)
  File "/home/afsoon/Houston/houston/sandbox.py", line 198, in run
    self._stop()
  File "/home/afsoon/Houston/houston/ardu/sandbox.py", line 154, in _stop
    block=True)
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/bugzoo/mgr/container.py", line 566, in command
    cmd_original, code, time_running, output)
Message: 'finished executing command: %s. (exited with code %d and took %.2f seconds.)\n%s'
```

**Comment by ChrisTimperley** [comment]
That's very strange. That seems to suggest that `code = self.__api_docker.exec_inspect(exec_id)['ExitCode']` evaluates to `None` (i.e., there is no exit code). Having said that, `bugzoo.mgr.container.command` isn't exactly the nicest method.
