### ISSUE TITLE
bugzoo build issue : failed to build Docker image: squareslab/manybugs:base

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/BugZoo#314]
I'm trying to run the example bugzoo bug build from the documentation, but running into issues.  See below docker image issues with squareslab/manybugs:base

I am just starting to debug and triple-checking your documentation to ensure that I have set up my system appropriately for bugzoo.  

My system: Ubuntu 18.10
bss-lab-1@bsslab1-Precision-Tower-5810:\~/BugZoo/manyBugs-repo-22-01-2019$ which python
**/home/bss-lab-1/.pyenv/shims/python**
bss-lab-1@bsslab1-Precision-Tower-5810:\~/BugZoo/manyBugs-repo-22-01-2019$ python --version
**Python 2.7.15+**
bss-lab-1@bsslab1-Precision-Tower-5810:\~/BugZoo/manyBugs-repo-22-01-2019$ bugzoo source list

**| Source           | Type   | URL                                        | Location                                                           | Version   |
|------------------+--------+--------------------------------------------+--------------------------------------------------------------------+-----------|
| another-manybugs | Local  | -                                          | /home/bss-lab-1/BugZoo/manyBugs-repo-22-01-2019                    | -         |
| manybugs         | Remote | https://github.com/squaresLab/ManyBugs     | /home/bss-lab-1/.bugzoo/sources/github_com_squaresLab_ManyBugs     | ad83bd9a  |
| genprog          | Remote | https://github.com/squaresLab/genprog-code | /home/bss-lab-1/.bugzoo/sources/github_com_squaresLab_genprog-code | 7a2d24a5  |**

```
bss-lab-1@bsslab1-Precision-Tower-5810:~/BugZoo/manyBugs-repo-22-01-2019$ bugzoo bug build manybugs:libtiff:2005-12-14-6746b87-0d3d51d
building bug: manybugs:libtiff:2005-12-14-6746b87-0d3d51d
Step 1/12 : FROM ubuntu:14.04

 ---> 5dbc3f318ea5
Step 2/12 : MAINTAINER Chris Timperley "christimperley@gmail.com"

 ---> Using cache
 ---> 161988c4c2e1
Step 3/12 : RUN apt-get update &&     apt-get install --no-install-recommends -y sudo &&     useradd -ms /bin/bash docker &&     echo 'docker ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&     adduser docker sudo &&     apt-get clean &&     mkdir -p /home/docker &&     sudo chown -R docker /home/docker &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

 ---> Running in c234c6e2fd61


================================================================================
An error occurred during execution:

  failed to build Docker image: squareslab/manybugs:base

See log file for details: /home/bss-lab-1/.bugzoo/logs/2019-01-28_10:30:34.bugzoo.log

bss-lab-1@bsslab1-Precision-Tower-5810:~/BugZoo/manyBugs-repo-22-01-2019$ tail -n 25 /home/bss-lab-1/.bugzoo/logs/2019-01-28_10\:30\:34.bugzoo.log 
DEBUG:bugzoo.mgr.build:2019-01-28 10:30:43,582: request to build image: squareslab/manybugs:libtiff-2005-12-14-6746b87-0d3d51d
INFO:bugzoo.mgr.build:2019-01-28 10:30:43,582: building dependent image: squareslab/manybugs:libtiff
DEBUG:bugzoo.mgr.build:2019-01-28 10:30:43,582: request to build image: squareslab/manybugs:libtiff
INFO:bugzoo.mgr.build:2019-01-28 10:30:43,582: building dependent image: squareslab/manybugs:base
DEBUG:bugzoo.mgr.build:2019-01-28 10:30:43,582: request to build image: squareslab/manybugs:base
INFO:bugzoo.mgr.build:2019-01-28 10:30:43,582: building image: squareslab/manybugs:base
ERROR:bugzoo.cli.app:2019-01-28 10:30:44,216: An error occurred
Traceback (most recent call last):
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/cli/app.py", line 72, in main
    app.run()
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 808, in _dispatch
    return func()
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/cli/controllers/bug.py", line 100, in build
    bugs.build(bug)
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/mgr/bug.py", line 82, in build
    quiet=quiet)
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/mgr/build.py", line 99, in build
    self.build(instructions.depends_on, force=force, quiet=quiet)
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/mgr/build.py", line 99, in build
    self.build(instructions.depends_on, force=force, quiet=quiet)
  File "/home/bss-lab-1/.local/lib/python3.6/site-packages/bugzoo/mgr/build.py", line 131, in build
    raise ImageBuildFailed(name, log)
bugzoo.exceptions.ImageBuildFailed: failed to build Docker image: squareslab/manybugs:base

```

**Comment by pdreiter** [comment]
Quick redress - updated python to 3.7.2 in pyenv, but still has the same failing signature.

**Comment by pdreiter** [comment]
Looks like my docker service was killed.  Restarting fixed this issue.
