### ISSUE TITLE
Exception when listing tools (Mac OS x)

### ISSUE THREAD

**Issue by rvantonder** [squaresLab/BugZoo#64]
```
./repairbox list tools                                                                                                                      [13:11:46]
Traceback (most recent call last):
  File "./repairbox", line 846, in <module>
    args.func(args)
  File "./repairbox", line 808, in <lambda>
    list_parser.set_defaults(func=lambda args: rbox.list(args.kind, args.quiet))
  File "./repairbox", line 630, in list
    print(lister[kind]())
  File "./repairbox", line 629, in <lambda>
    'tools': lambda: self.list_tools(quiet)})
  File "./repairbox", line 569, in list_tools
    tbl.append([name, tool.image, tool.is_installed()])
  File "./repairbox", line 484, in is_installed
    return subprocess.call(cmd, stdout=DEVNULL, stderr=DEVNULL) == 0
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ChrisTimperley** [comment]
This code is long since dead 💀
