### ISSUE TITLE
First manybugs:php bug fails to build with segfault (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jlacomis** [squaresLab/BugZoo#66]
I'm getting a segfault and failure to build when trying to install the first php bug (but not the second or third):

```
[14:02] gs17931:RepairBox :) > ./repairbox install bug manybugs:php
building image: 2011-01-06-e7a1d5004e-3571c955b5
Failed to build image: squareslab/repairbox:manybugs-php-2011-01-06-e7a1d5004e-3571c955b5
Saved error log to: 1509995041.rbox.crash
```
```
[14:05] gs17931:RepairBox :( > tail -15 1509995041.rbox.crash 
Generating phar.phar
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
invertedregexiterator.inc
directorygraphiterator.inc
pharcommand.inc
clicommand.inc
directorytreeiterator.inc
make: *** [ext/phar/phar.phar] Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/experiment/prepare.py", line 62, in <module>
    cmd('cd /experiment/src && make -j{}'.format(multiprocessing.cpu_count()))
  File "/experiment/prepare.py", line 24, in cmd
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /experiment/src && make -j4' returned non-zero exit status 2
The command '/bin/sh -c /experiment/prepare.py' returned a non-zero code: 1
```

[1509995041.rbox.crash.txt](https://github.com/squaresLab/RepairBox/files/1447445/1509995041.rbox.crash.txt)

**Comment by ChrisTimperley** [comment]
Seems to be fixed. Thanks for reporting it!
