### ISSUE TITLE
NameError when removing sources

### ISSUE THREAD

**Issue by jlacomis** [squaresLab/BugZoo#76]
I am getting `NameError: name 'ds' is not defined` when trying to remove a source:

```
[12:04] gs17931:RepairBox :( > repairbox source list

Source    URL                                         Version
--------  ------------------------------------------  ---------
manybugs  https://github.com/ChrisTimperley/ManyBugs  3e87b318
genprog   https://bitbucket.org/ChrisTimperley/GP3    0c5d9255
[12:04] gs17931:RepairBox :) > repairbox source remove manybugs
Traceback (most recent call last):
  File "/usr/local/bin/repairbox", line 9, in <module>
    load_entry_point('repairbox==0.0.1', 'console_scripts', 'repairbox')()
  File "/usr/local/lib/python3.5/dist-packages/repairbox-0.0.1-py3.5.egg/repairbox/cli.py", line 348, in main
  File "/usr/local/lib/python3.5/dist-packages/repairbox-0.0.1-py3.5.egg/repairbox/cli.py", line 207, in <lambda>
  File "/usr/local/lib/python3.5/dist-packages/repairbox-0.0.1-py3.5.egg/repairbox/cli.py", line 30, in remove_source
NameError: name 'ds' is not defined
```

**Comment by ChrisTimperley** [comment]
Should be fixed. Thanks for reporting!
